import nordicUtils

class Nordic:
    BBP_LED_ENABLE_WHITE = 0xa0
    BBP_LED_ENABLE_IR = 0xa1
    BBP_LED_ENABLE_UV = 0xa2
    BBP_LED_DISABLE	= 0xa3
    BBP_LED_SET_CURRENT = 0xa4
    BBP_STATUS_LED_ENABLE = 0xad
    BBP_STATUS_LED_DISABLE = 0xae
    BBP_LED_SET_STATUS_LED = 0xaf
    
    BBP_BAT_GET_VOLTAGE = 0xb0

    BBP_PIM_REPORT_ALIVE = 0xc0
    BBP_PIM_SET_WD_TIMEOUT = 0xc1
    BBP_PIM_WAKE_UP_IN_SEC = 0xc2
    BBP_PIM_WAIT_FOR_SHUTDOWN = 0xc3
    BBP_PIM_HARD_RESET = 0xc4
    BBP_PIM_WAKEUP_BY_VOLTAGE = 0xc5
    BBP_PIM_SET_DEFAULT_OFF_TIME = 0xc6

    BBP_TOF_LIGHT_LEVEL = 0xd0

    BBP_DEBUG_SYSTIME = 0xf0
    BBP_DEBUG_WATCHDOG = 0xf1

